databasecli = {
    'hello': 'Hello, how can I assist you?',
    'how are you': 'I am doing well, thank you!',
    'weather': 'The weather is sunny today.',
    'goodbye': 'Goodbye! Have a nice day.',
    'default': 'Sorry, I dont have an appropriate response.',
    'what is your name': 'My name is ghadaam.',
    'where are you from': 'I am an AI language model developed by sahandmohammadrezaii.',
    'how old are you': 'I am an artificial intelligence and do not have an age.',
    'tell me a joke': 'Why dont scientists trust atoms? Because they make up everything!',
    'what is the meaning of life': 'The meaning of life is subjective and can vary for each individual.',
    'who is your favorite celebrity': 'As an AI, I do not have preferences.',
    'can you sing a song': 'I can not sing but I can help you with any questions you have!',
    'tell me about yourself': 'I am an AI language model trained to provide information and assist with various inquiries.',
    'what is the capital of France': 'The capital of France is Paris.',
    'how do I change my password': 'To change your password, you can go to the settings menu and look for the password change option.',
    'how can I contact customer support': 'You can contact our customer support team by calling the following number: XXX-XXXXXXX.',
    'what is the latest news': 'The latest news can be found on various news websites or by tuning in to news channels.',
    'how do I delete my account': 'To delete your account, you can go to the account settings and look for the delete account option.',
    'what are your hobbies': 'As an AI, I do not have hobbies, but I enjoy helping and providing information to users.',
    'tell me a fun fact': 'Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!',
    'what is the largest planet in our solar system': 'The largest planet in our solar system is Jupiter.',
    'how do I reset my password': 'To reset your password, you can click on the "Forgot Password" link on the login page and follow the instructions.',
    'what is the population of China': 'As of my knowledge cutoff in September 2021, the population of China is approximately 1.4 billion.',
    'how do I unsubscribe from newsletters': 'To unsubscribe from newsletters, you can usually find an "Unsubscribe" link at the bottom of the email.',
    'what is the currency of Japan': 'The currency of Japan is the Japanese yen (JPY).',
    'how do I book a flight': 'You can book a flight by visiting airline websites or using online travel agencies.',
    'what is the tallest mountain in the world': 'The tallest mountain in the world is Mount Everest.',
}