databasecli = {
    'hello': 'Hello, how can I assist you?',
    'how are you': 'I am doing well, thank you!',
    'weather': 'The weather is sunny today.',
    'goodbye': 'Goodbye! Have a nice day.',
    'default': 'Sorry, I dont have an appropriate response.',
    'what is your name': 'My name is ghadaam.',
    'where are you from': 'I am an AI language model developed by sahandmohammadrezaii.',
    'how old are you': 'I am an artificial intelligence and do not have an age.',
    'tell me a joke': 'Why dont scientists trust atoms? Because they make up everything!',
    'what is the meaning of life': 'The meaning of life is subjective and can vary for each individual.',
    'who is your favorite celebrity': 'As an AI, I do not have preferences.',
    'can you sing a song': 'I can not sing but I can help you with any questions you have!',
    'tell me about yourself': 'I am an AI language model trained to provide information and assist with various inquiries.',
    'what is the capital of France': 'The capital of France is Paris.',
    'how do I change my password': 'To change your password, you can go to the settings menu and look for the password change option.',
    'how can I contact customer support': 'You can contact our customer support team by calling the following number: XXX-XXXXXXX.',
    'what is the latest news': 'The latest news can be found on various news websites or by tuning in to news channels.',
    'how do I delete my account': 'To delete your account, you can go to the account settings and look for the delete account option.',
    'what are your hobbies': 'As an AI, I do not have hobbies, but I enjoy helping and providing information to users.',
    'tell me a fun fact': 'Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!',
    'what is the largest planet in our solar system': 'The largest planet in our solar system is Jupiter.',
    'how do I reset my password': 'To reset your password, you can click on the "Forgot Password" link on the login page and follow the instructions.',
    'what is the population of China': 'As of my knowledge cutoff in September 2021, the population of China is approximately 1.4 billion.',
    'how do I unsubscribe from newsletters': 'To unsubscribe from newsletters, you can usually find an "Unsubscribe" link at the bottom of the email.',
    'what is the currency of Japan': 'The currency of Japan is the Japanese yen (JPY).',
    'how do I book a flight': 'You can book a flight by visiting airline websites or using online travel agencies.',
    'what is the tallest mountain in the world': 'The tallest mountain in the world is Mount Everest.',
    'what is programming': 'Programming is the process of writing instructions for a computer to perform specific tasks. It involves using programming languages to create software and applications.',
    'what are programming languages': 'Programming languages are formal languages used to communicate instructions to a computer. They have syntax and semantics that allow programmers to write code that the computer can understand and execute.',
    'what is an algorithm': 'An algorithm is a step-by-step procedure or a set of rules for solving a specific problem or accomplishing a specific task. It is a fundamental concept in computer science and programming.',
    'what is a variable': 'In programming, a variable is a named storage location that holds a value. It acts as a container for storing and manipulating data during the execution of a program.',
    'what is a function': 'In programming, a function is a named block of code that performs a specific task or a set of instructions. It helps in organizing and reusing code by encapsulating a particular functionality.',
    'what is the capital of Iran': 'The capital of Iran is Tehran.',
    'what is the population of Iran': 'As of my knowledge cutoff in September 2021, the population of Iran is approximately 83 million.',
    'what is the official language of Iran': 'The official language of Iran is Persian (Farsi).',
    'what are some famous landmarks in Iran': 'Some famous landmarks in Iran include Persepolis Naqsh-e Jahan Square, Golestan Palace, and Azadi Tower.',
    'what is the currency of Iran': 'The currency of Iran is the Iranian Rial (IRR).',
    'what are some traditional foods in Iran': 'Some traditional foods in Iran include kebab, ghormeh sabzi tahchin, and fesenjan.',
    'what is the climate like in Iran': 'Iran has a diverse climate, ranging from arid and semi-arid in the central and eastern regions to Mediterranean and subtropical in the northern and western regions.',
    'what is the official religion of Iran': 'The official religion of Iran is Islam, with the majority of Iranians being followers of Shia Islam.',
    'what is the national symbol of Iran': 'The national symbol of Iran is the Lion and Sun, which was used as the emblem of Persia for centuries.',
    'what is JavaScript': 'JavaScript is a programming language that is commonly used for creating interactive web pages and web applications.',
    'what are the features of JavaScript': 'Some features of JavaScript include dynamic typing prototype-based object-orientation, and support for functions as first-class objects.',
    'what are variables in JavaScript': 'In JavaScript, variables are used to store data values They can be declared using the "var", "let", or "const" keywords.',
    'what are data types in JavaScript': 'JavaScript has several data types, including number string, boolean null undefined, object, and symbol.',
    'what are operators in JavaScript': 'Operators in JavaScript are used to perform operations on variables and values. They include arithmetic, assignment, comparison, logical, and more.',
    'what are functions in JavaScript': 'Functions in JavaScript are reusable blocks of code that can be called to perform a specific task. They can take input values (parameters) and return output values.',
    'what is an array in JavaScript': 'An array in JavaScript is a data structure that allows you to store multiple values in a single variable. It is declared using square brackets [] and can hold elements of different data types.',
    'what is an object in JavaScript': 'In JavaScript, an object is a collection of key-value pairs. It is a versatile data structure that can represent real-world entities and has properties and methods.',
    'what is a conditional statement in JavaScript': 'A conditional statement in JavaScript allows you to make decisions in your code based on certain conditions. The "if-else" statement is commonly used for this purpose.',
    'what is a loop in JavaScript': 'A loop in JavaScript allows you to repeatedly execute a block of code. The "for" loop and "while" loop are commonly used looping constructs.',
    'what is event handling in JavaScript': 'Event handling in JavaScript involves responding to user actions or events, such as clicks or keystrokes, by executing specific code. It is commonly used to add interactivity to web pages.',
    'what is DOM manipulation in JavaScript': 'DOM manipulation in JavaScript involves accessing and modifying the Document Object Model (DOM) of a web page. It allows you to dynamically change the content and appearance of web pages.',
    'what is AJAX in JavaScript': 'AJAX (Asynchronous JavaScript and XML) is a technique in JavaScript that allows you to update parts of a web page without reloading the entire page. It enables asynchronous communication with a server.',
    'what is JSON in JavaScript': 'JSON (JavaScript Object Notation) is a lightweight data format that is often used for data interchange between a server and a web application. It is based on a subset of JavaScript syntax.',
    'what is a callback function in JavaScript': 'A callback function in JavaScript is a function that is passed as an argument to another function and is invoked or called at a specific point in the execution of that function.',
    'what is a promise in JavaScript': 'A promise in JavaScript is an object that represents the eventual completion or failure of an asynchronous operation. It allows you to handle asynchronous code in a more organized and readable way.',
    'what is ECMAScript': 'ECMAScript is the standardized specification of the JavaScript programming language. It defines the syntax, types, and behavior of JavaScript.',
    'what are some popular JavaScript frameworks': 'Some popular JavaScript frameworks include React, Angular, and Vue.js. These frameworks provide tools and libraries to simplify the development of web applications.',
    'what are some popular JavaScript libraries': 'Some popular JavaScript libraries include jQuery, Lodash, and Moment.js. These libraries provide reusable functions and utilities to enhance JavaScript development.',
    'what is Node.js': 'Node.js is a runtime environment that allows you to run JavaScript code outside of a web browser. It is commonly used for server-side and command-line applications.',
    'what is npm': 'npm (Node Package Manager) is the default package manager for Node.js. It allows you to install, manage, and share JavaScript packages and dependencies.',
    'what is TypeScript': 'TypeScript is a superset of JavaScript that adds static typing and other features to the language. It is designed to enhance the development of large-scale JavaScript applications.',
    'what is Babel': 'Babel is a toolchain that is mainly used to convert ECMAScript 2015+ (ES6+) code into backward-compatible versions of JavaScript. It allows you to use the latest JavaScript features while ensuring compatibility with older browsers.',
    }